apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-09-19T13:06:48Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "2491906"
  uid: 4be61513-c62f-49ef-8c59-0f15b443f805
spec:
  clusterIP: 10.104.8.163
  clusterIPs:
  - 10.104.8.163
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32404
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.132.242.193
