apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: yashassamaga/msv2-currency-exchange-service:0.0.2-kubernetes
        imagePullPolicy: IfNotPresent
        name: msv2-currency-exchange-service
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8000
        livenessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8000
      restartPolicy: Always
